baseURL = '/'
languageCode = 'en-us'
title = 'uuidgen.dev'
theme = 'terminal'

[params]
title = "uuidgen.dev"
centerTheme = true
contentTypeName = "posts"
logoText = "uuidgen.dev"
showLastUpdated = true

[params.twitter]
creator = "Cole_MacKenzie"
site = "https://cmackenzie1.github.io"

[languages]
  [languages.en]
    title = "uuidgen.dev"
    subtitle = "UUID-as-a-Service"
    keywords = "uuid-as-a-service, uuid, rest, api, guid, javascript, typescript"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "uuidgen.dev"
      logoHomeLink = "/"


