name = "uuidgen-dev-production"
main = "src/index.ts"
compatibility_date = "2022-09-22"
account_id = "f5686db3c4f5b3e38b8f15b0561a28a8"
routes = [
    { pattern = "uuidgen.dev", custom_domain = true }
]

[[unsafe.bindings]]
type = "analytics_engine"
name = "requests"
dataset = "uuidgen_requests"

[[unsafe.bindings]]
type = "analytics_engine"
name = "stats"
dataset = "uuidgen_stats"

[[unsafe.bindings]]
type = "analytics_engine"
name = "logs"
dataset = "uuidgen_logs"
