name = "uuidgen-dev-development"
compatibility_date = "2021-11-05"
type = "javascript"
workers_dev = true

[env.production]
name = "uuidgen-dev-production"
workers_dev = false
zone_id = "6224548efd4ca921571ca105ccdead61"
route = "uuidgen.dev/*"

[build]
command = "yarn install && yarn build"

[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"
